### PR TITLE
fix(qwik-city): strip internal parameters for compare

### LINKED ISSUE #6660: [🐞] Breaking change introduced in 1.7.0 - `qaction` in url is appended using `routeAction` and `globalAction`
### Which component is affected?

Qwik Runtime

### Describe the bug

1.6.0 didn't have this issue

### Reproduction

> https://stackblitz.com/edit/qwik-starter-cidktr

Thanks @blecorre-mnp for the repro

### Steps to reproduce

> You can see that once you click on the submit buttons, you'll have the ```&qaction=...``` appended to the url.

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 96.05 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
    pnpm: 9.4.0 - /opt/homebrew/bin/pnpm
    bun: 1.1.18 - /opt/homebrew/bin/bun
  Browsers:
    Safari: 17.5
  npmPackages:
    @builder.io/qwik: ^1.7.0 => 1.7.0
    @builder.io/qwik-city: ^1.7.0 => 1.7.0
    typescript: 5.5.3 => 5.5.3
    undici: ^6.19.2 => 6.19.2
    vite: ^5.3.3 => 5.3.3
```

### Additional Information

_No response_

### LINKED ISSUE #6677: [🐞] in dev mode, ignore dist/
### Which component is affected?

Qwik Runtime

### Describe the bug

When running in dev mode, and there's a stale dist/ folder with SSG files in there, those files get served.

In dev, only public/ should be served.

### Reproduction

not yet

### Steps to reproduce

drive by issue creation, no repro, could be just an issue with this proprietary repo

### System Info

```shell
macos with latest qwik
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by wmertens**
Followup for #6410 and #6687
Fixes #6660
Fixes #6677

### CODE REVIEW

**Comment by shairez** [comment]
seems like a duplicate of #6687 no?

btw did you see this?
https://github.com/QwikDev/qwik/pull/6687#issuecomment-2229606481

**Review by gioboa — APPROVED** [review]
That's great 👏 thanks @wmertens

File: packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts [hunk 1]
```diff
@@ -407,7 +407,9 @@ export function getPathname(url: URL, trailingSlash: boolean | undefined) {
       url.pathname = url.pathname.slice(0, -1);
     }
   }
-  return url.toString().substring(url.origin.length);
+  // strip internal search params
+  const search = url.search.slice(1).replaceAll(/&?q(action|data|func)=[^&]+/g, '');
```
Comment (octet-stream) [inline packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts:411]: I would still suggest using URLSearchParams and constants instead. But they are in runtime package.

Something like this:

```ts
[QACTION_KEY, QFN_KEY, QDATA_KEY].forEach(key => url.searchParams.delete(key))
```

The browsers and other runtimes have API that makes it easy to work with search params, no need to wrestle with strings.

Comment (wmertens) [reply packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts:411]: I first had this, but even when it's fully supported it will change the search string a bit. That's why the test doesn't have `=` for the second parameter.

When you remove searchParams, it will convert the rest to search parameters and `?myquery` becomes `?myquery=`. Since we're a framework I want to avoid messing with the URL whenever we can.

**Comment by shirotech** [comment]
Very nice, hope this can be released soon. Have been waiting for a specific fix for awhile in anticipation. Great work team!
