### PR TITLE
fix(qwik-city): Avoided unexpected caching for dynamic q-data

### LINKED ISSUE #6789: [🐞] SPA reload randomly fails to update the values loaded by the `routeLoader$`
### Which component is affected?

Qwik City (routing)

### Describe the bug

I am making app that uses `routeLoader$` for loading dynamic data.
I found the SPA reload sometimes fails to update the data like this.

https://github.com/user-attachments/assets/a88f5efb-625d-4b67-8c1f-c87978e3cc29

Note that the 3rd reload (around 0:07 at the video) trigger the call of the route loader and logged the count at server side but doesn't change the values in client side.
The next click updates the values but doesn't trigger the call.

I expected the each reload can update the value.

### Reproduction

https://github.com/genki/qtest

### Steps to reproduce

Please clone the repo above and
```sh
pnpm i
pnpm run dev
```
then open `http://localhost:5173/`

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 117.77 MB / 24.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.12.1 - /opt/homebrew/opt/node@20/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /opt/homebrew/opt/node@20/bin/npm
    pnpm: 9.6.0 - ~/Library/pnpm/pnpm
    bun: 1.1.21 - ~/.bun/bin/bun
  Browsers:
    Chrome: 127.0.6533.101
    Safari: 17.5
  npmPackages:
    @builder.io/qwik: ^1.8.0 => 1.8.0 
    @builder.io/qwik-city: ^1.8.0 => 1.8.0 
    typescript: 5.4.5 => 5.4.5 
    undici: * => 6.19.5 
    vite: ^5.2.10 => 5.3.5
```

### Additional Information

Interestingly, this behaviour doesn't occur at the stackbliz.
https://stackblitz.com/edit/github-ahtxgw?file=src%2Froutes%2Findex.tsx

### PR DESCRIPTION
**Pull request by genki**
# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests / types / typos
- [ ] Infra

# Description

Inside the `loadClientData`, the `fetch()` had been called without the cache control options even if it is needed to avoid caching.
So I added it if the `opts.clearCache` is set.

Fixes #6789

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have ran `pnpm change` and documented my changes
- [ ] I have made corresponding changes to the Qwik docs
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

File: packages/qwik/src/optimizer/src/qwik-binding-map.ts [hunk 1]
```diff
@@ -30,15 +30,5 @@ export const QWIK_BINDING_MAP = {
         "platformArchABI": "qwik.win32-x64-msvc.node"
       }
     ]
-  },
```
Comment (wmertens) [inline packages/qwik/src/optimizer/src/qwik-binding-map.ts:33]: Don't remove this

File: packages/docs/src/routes/api/qwik/index.md [hunk 2]
```diff
@@ -3679,7 +3679,7 @@ Options for the prefetch service worker.
 </tbody></table>
 **Returns:**
 
-[JSXNode](#jsxnode)&lt;'script'&gt;
+JSXNode&lt;'script'&gt;
```
Comment (wmertens) [inline packages/docs/src/routes/api/qwik/index.md:3682]: Can you run `pnpm api.update` so it doesn't do this? Something in the build causes this, I wish it didn't :(

File: packages/docs/src/repl/worker/app-bundle-client.ts [hunk 3]
```diff
@@ -19,7 +19,7 @@ export const appBundleClient = async (
     srcInputs: getInputs(options),
     // Older versions don't support `segment`
     entryStrategy:
-      options.entryStrategy.type === 'segment' ? { type: 'hook' } : options.entryStrategy,
+      options.entryStrategy?.type === 'segment' ? { type: 'hook' } : options.entryStrategy,
```
Comment (wmertens) [inline packages/docs/src/repl/worker/app-bundle-client.ts:22]: Oh wow, it's not always defined?

File: packages/qwik-city/src/runtime/src/use-endpoint.ts [hunk 4]
```diff
@@ -28,7 +28,7 @@ export const loadClientData = async (
   let resolveFn: () => void | undefined;
 
   if (!qData) {
-    const fetchOptions = getFetchOptions(opts?.action);
+    const fetchOptions = getFetchOptions(opts?.action, opts?.clearCache) ?? {};
```
Comment (wmertens) [inline packages/qwik-city/src/runtime/src/use-endpoint.ts:31]: Why the {}? No need to create objects here, no? And if it is really needed, better to add it in getFetchOptions

**Review by wmertens — CHANGES_REQUESTED** [review]
The fix looks great but we need a few changes

File: packages/qwik/src/optimizer/src/qwik-binding-map.ts (hunk 1 above)
Comment (genki) [reply packages/qwik/src/optimizer/src/qwik-binding-map.ts:33]: I see. This might have been automatically modified by `pnpm run build.full`.
I will manually revert this, but it could solve?
I am a bit confusion about the current build process has changed from before.

File: packages/docs/src/repl/worker/app-bundle-client.ts (hunk 3 above)
Comment (genki) [reply packages/docs/src/repl/worker/app-bundle-client.ts:22]: I had to fix this in order to suppress error from the eslint because it is defined as `entryStrategy?: EntryStrategy;`

File: packages/qwik-city/src/runtime/src/use-endpoint.ts (hunk 4 above)
Comment (genki) [reply packages/qwik-city/src/runtime/src/use-endpoint.ts:31]: Yeah, this is not needed. I remove it.
This is a remnant of a tentative implementation that was modifying opts inplace.

File: packages/docs/src/repl/worker/app-bundle-client.ts (hunk 3 above)
Comment (wmertens) [reply packages/docs/src/repl/worker/app-bundle-client.ts:22]: Weird that TS didn't encounter this problem when it got merged

**Review by wmertens — APPROVED** [review]
LGTM 🙌 Thanks!
