### PR TITLE
fix: replace chunkFileNames logic

### LINKED ISSUE #6673: [🐞] Unability to change chunkFileNames with vite.build.rollupOptions.chunkFileNames
### Which component is affected?

Qwik Runtime

### Describe the bug

I believe this was introduce in #6588 @gioboa

In previous versions, I was able to add 
```tsx
  let output: any = {};
  if (!isDev) {
    // Client-specific configuration
    output = {
      // Customize the client build structure
      entryFileNames: ({ name }: any) => {
        if (name.startsWith('entry')) {
          return '[name].js';
        }
        return `build/[name]-[hash].js`;
      },
      chunkFileNames: () => {
        return `build/[name]-[hash].js`;
      },
      assetFileNames: `build/[name]-[hash].[ext]`,
    };
  }
  ```
  in a vite.config
  
  with 
  
  ```tsx
      build: {
      rollupOptions: {
        output,
      },
    },
```

But now when running preview with it,
    
I get
   > x Build failed in 5.55s
TypeError [PLUGIN_ERROR]: [vite-plugin-qwik-post] The "path" argument must be of type string. Received function chunkFileNames
    at Object.dirname (node:path:1279:5)
    at Object.handler (/Users/maieul/dev/qwik-ui/node_modules/.pnpm/@builder.io+qwik@https+++pkg.pr.new+@builder.io+qwik@7fdea60_@types+node@20.12.12_sass@1.77.4_v2qpm4luyvgabz4seeshjuuzrq/node_modules/@builder.io/qwik/optimizer.cjs:3561:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'PLUGIN_ERROR',
  pluginCode: 'ERR_INVALID_ARG_TYPE',
  plugin: 'vite-plugin-qwik-post',
  hook: 'generateBundle'
}

### Reproduction

https://github.com/qwikifiers/qwik-ui

### Steps to reproduce

- Go to apps/website/vite.config.ts
- Uncomment comments
- Run preview

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 80.64 MB / 24.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 22.2.0 - /opt/homebrew/bin/node
    npm: 10.7.0 - /opt/homebrew/bin/npm
    pnpm: 9.5.0 - /usr/local/bin/pnpm
    bun: 1.1.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
```

### Additional Information

I believe this is caused in packages/qwik/src/optimizer/src/plugins/vite.ts either by removal of 

```tsx
output: normalizeRollupOutputOptions(
            path,
            )
```
line 337

or type casting in
```tsx
          const filePath = sys.path.dirname(_.chunkFileNames as string);
```
line 564

### PR DESCRIPTION
**Pull request by gioboa**
Fix #6673 

# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

File: packages/qwik/src/optimizer/src/plugins/vite.ts [hunk 1]
```diff
@@ -558,23 +558,26 @@ export function qwikVite(qwikViteOpts: QwikVitePluginOptions = {}): any {
...
           });
+          const assetsDir = qwikPlugin.getOptions().assetsDir || '';
+          const useAssetsDir = !!assetsDir && assetsDir !== '_astro';
           const sys = qwikPlugin.getSys();
-          const filePath = sys.path.dirname(_.chunkFileNames as string);
           this.emitFile({
             type: 'asset',
-            fileName: sys.path.join(filePath, `q-bundle-graph-${manifest.manifestHash}.json`),
+            fileName: sys.path.join(
+              useAssetsDir ? assetsDir : '',
```
Comment (shairez) [inline packages/qwik/src/optimizer/src/plugins/vite.ts:567]: Looks like we could combine the `useAssetsDir ? ...` logic into one parameter for both places 

Maybe something like `buildPath` or something alike

Comment (gioboa) [reply packages/qwik/src/optimizer/src/plugins/vite.ts:567]: I like it

**Review by shairez — APPROVED** [review]

**Comment by maiieul** [comment]
Tested this on Qwik UI, I'm getting some errors:
image

> ✘ [ERROR] Missing "./vite" specifier in "@builder.io/qwik" package [plugin externalize-deps]

    node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1374:27:
      1374 │         let result = await callback({
           ╵                            ^

    at e (file:///Users/maieul/dev/qwik-ui/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.12_sass@1.77.4_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47597:25)
    at n (file:///Users/maieul/dev/qwik-ui/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.12_sass@1.77.4_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47597:627)
    at o (file:///Users/maieul/dev/qwik-ui/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.12_sass@1.77.4_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47597:1297)
    at resolveExportsOrImports (file:///Users/maieul/dev/qwik-ui/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.12_sass@1.77.4_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48287:20)
    at resolveDeepImport (file:///Users/maieul/dev/qwik-ui/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.12_sass@1.77.4_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48306:31)
    at tryNodeResolve (file:///Users/maieul/dev/qwik-ui/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.12_sass@1.77.4_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48031:20)
    at resolveByViteResolver (file:///Users/maieul/dev/qwik-ui/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.12_sass@1.77.4_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:68607:32)
    at file:///Users/maieul/dev/qwik-ui/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.12_sass@1.77.4_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:68639:40
    at requestCallbacks.on-resolve (/Users/maieul/dev/qwik-ui/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1374:28)
    at handleRequest (/Users/maieul/dev/qwik-ui/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:732:17)

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1293:20:
      1293 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/maieul/dev/qwik-ui/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.12_sass@1.77.4_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:68624:27)
    at handlePlugins (/Users/maieul/dev/qwik-ui/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1293:21)
    at buildOrContextImpl (/Users/maieul/dev/qwik-ui/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:979:5)
    at Object.buildOrContext (/Users/maieul/dev/qwik-ui/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:788:5)
    at /Users/maieul/dev/qwik-ui/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:2215:15
    at new Promise (<anonymous>)
    at Object.build (/Users/maieul/dev/qwik-ui/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:2214:25)
    at build (/Users/maieul/dev/qwik-ui/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:2047:51)
    at bundleConfigFile (file:///Users/maieul/dev/qwik-ui/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.12_sass@1.77.4_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:68583:26)

  The plugin "externalize-deps" was triggered by this import

    apps/website/vite.config.ts:1:317:
      1 │ ...injected_original_import_meta_url = "file:///Users/maieul/dev/qwik-ui/apps/website/vite.config.ts";import { qwikCity } from '@builder.io/qwik-city/vite';
        ╵                                                                                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

failed to load config from /Users/maieul/dev/qwik-ui/apps/website/vite.config.ts

and 

> node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1374:27: ERROR: [plugin: externalize-deps] Missing "./vite" specifier in "@builder.io/qwik" package
Pass --verbose to see the stacktrace.
