### PR TITLE
fix: export SVG type

### LINKED ISSUE #7212: [🐞] V2: Important types like `SVGAttributes` are not exported
### Which component is affected?

Qwik Runtime

### Describe the bug

In some components like [this one](https://github.com/fabian-hiller/valibot/blob/main/website/src/icons/AngleRightIcon.tsx#L3) I need to access the generated JSX types but they are not exported in the build of Qwik core in `dist/core-internal.d.ts`.

### Reproduction

https://stackblitz.com/edit/github-o2f6fj9n?file=src%2Fcomponents%2FCheckIcon.tsx

### Steps to reproduce

_No response_

### System Info

```shell
-
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by JerryWu1234**
fixes #7212 
# What is it?

export a type of `SVGAttributes`.

# Description

# Checklist

- [x] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [x] I performed a self-review of my own code
- [x] I added a changeset with `pnpm change`
- [x] I made corresponding changes to the Qwik docs
- [x] I added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by JerryWu1234** [comment]
@wmertens please help to review this PR

File: packages/qwik/public.d.ts [hunk 1]
```diff
@@ -72,3 +72,5 @@ export {
   version,
   withLocale,
 } from './dist/core-internal';
+
+export type * from './dist/core-internal';
```
Comment (wmertens) [inline packages/qwik/public.d.ts:76]: The reason I split the internal and public was so that we wouldn't have many internal types as public API.

So every export that we want to expose must be listed separately.

**Review by wmertens — CHANGES_REQUESTED** [review]

**Review by wmertens — APPROVED** [review]
